dist: xenial
language: python
python:
 - 3.4
 - 3.6
 - 3.7
php:
 - 7.2
cache: pip
notifications:
  irc:
    channels:
      - "irc.oftc.net#OpenRailwayMap"
    on_success: change
    on_failure: change
    use_notice: false
    skip_join: false
addons:
  apt:
    packages:
    - libxml2-utils
    - python3-cairo
    - python3-ply
    - python-imaging
    - python-cairo
    - python-ply
    - python-rsvg
install:
 - pip install 'cairocffi<1' 'pillow<6' ply pojson
script:
 - make
 - make check
